remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

title: CIPTA KYUEM
description: Homepage for CIPTA (Create, Inspire, Progress Together for All) at KYUEM

show_downloads: false